# Generated by Django 4.2.2 on 2023-07-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_info_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
